MODEL:
  TYPE: resnest
  NAME: resnest18
  NUM_CLASSES: 1000
  PRETRAINED: https://github.com/zhanghang1989/ResNeSt/releases/download/weights_step1/resnest50-528c19ca.pth

  RESNEST:
    LAYERS: [2,2,2,2]
    RADIX: 2
    GROUPS: 1
    BOTTLENECK_WIDTH: 64
    DEEP_STEM: True
    STEM_WIDTH: 32
    AVG_DOWN: True
    AVD: True
    AVD_FIRST: False
