MODEL:
  TYPE: resnest
  NAME: resnest101
  NUM_CLASSES: 1000
  PRETRAINED: https://github.com/zhanghang1989/ResNeSt/releases/download/weights_step1/resnest101-22405ba7.pth

  RESNEST:
    LAYERS: [3,4,23,3]
    RADIX: 2
    GROUPS: 1
    BOTTLENECK_WIDTH: 64
    DEEP_STEM: True
    STEM_WIDTH: 64
    AVG_DOWN: True
    AVD: True
    AVD_FIRST: False