MODEL:
  TYPE: resnest
  NAME: resnest200
  NUM_CLASSES: 1000
  PRETRAINED: https://github.com/zhanghang1989/ResNeSt/releases/download/weights_step1/resnest200-75117900.pth

  RESNEST:
    LAYERS: [3,24,36,3]
    RADIX: 2
    GROUPS: 1
    BOTTLENECK_WIDTH: 64
    DEEP_STEM: True
    STEM_WIDTH: 64
    AVG_DOWN: True
    AVD: True
    AVD_FIRST: False