MODEL:
  TYPE: resnest
  NAME: resnest50_fast_2s1x64d
  NUM_CLASSES: 1000
  PRETRAINED: https://github.com/zhanghang1989/ResNeSt/releases/download/weights_step1/resnest50_fast_2s1x64d-44938639.pth

  RESNEST:
    LAYERS: [3,4,6,3]
    RADIX: 2
    GROUPS: 1
    BOTTLENECK_WIDTH: 64
    DEEP_STEM: True
    STEM_WIDTH: 32
    AVG_DOWN: True
    AVD: True
    AVD_FIRST: True