MODEL:
  TYPE: resnest
  NAME: resnest269
  NUM_CLASSES: 1000
  PRETRAINED: https://github.com/zhanghang1989/ResNeSt/releases/download/weights_step1/resnest269-0cc87c48.pth

  RESNEST:
    LAYERS: [3,30,48,8]
    RADIX: 2
    GROUPS: 1
    BOTTLENECK_WIDTH: 64
    DEEP_STEM: True
    STEM_WIDTH: 64
    AVG_DOWN: True
    AVD: True
    AVD_FIRST: False