MODEL:
  TYPE: resnest
  NAME: resnest50_fast_1s4x24d
  NUM_CLASSES: 1000
  PRETRAINED: https://github.com/zhanghang1989/ResNeSt/releases/download/weights_step1/resnest50_fast_1s4x24d-d4a4f76f.pth

  RESNEST:
    LAYERS: [3,4,6,3]
    RADIX: 1
    GROUPS: 4
    BOTTLENECK_WIDTH: 24
    DEEP_STEM: True
    STEM_WIDTH: 32
    AVG_DOWN: True
    AVD: True
    AVD_FIRST: True